<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-5U4E5L3" failures="0" tests="1" name="ErrorValidation Test" time="23.931" errors="0" timestamp="2024-03-29T12:11:58 IST">
  <testcase classname="RahulShettyAcademy.TestComponents.BaseTest" name="@BeforeMethod launchApplication" time="23.767">
    <failure type="org.openqa.selenium.remote.http.ConnectionFailedException" message="Unable to establish websocket connection to http://localhost:63115/devtools/browser/88886d4e-d5a1-4c64-9f51-2919bf1f8efb
Build info: version: &amp;apos;4.5.0&amp;apos;, revision: &amp;apos;fe167b119a&amp;apos;
System info: os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;11.0.21&amp;apos;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:63115/devtools/browser/88886d4e-d5a1-4c64-9f51-2919bf1f8efb
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.21'
Driver info: driver.version: ChromeDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:107)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:116)
at java.base/java.util.Optional.map(Optional.java:265)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:81)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:70)
at RahulShettyAcademy.TestComponents.BaseTest.initializationDriver(BaseTest.java:57)
at RahulShettyAcademy.TestComponents.BaseTest.launchApplication(BaseTest.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod launchApplication -->
  <testcase classname="RahulShettyAcademy.TestComponents.BaseTest" name="@AfterMethod tearDown" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at RahulShettyAcademy.TestComponents.BaseTest.tearDown(BaseTest.java:105)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="RahulShettyAcademy.Tests.ErrorValidationTest" name="LogInErrorValidation" time="0.0">
    <skipped/>
  </testcase> <!-- LogInErrorValidation -->
  <testcase classname="RahulShettyAcademy.Tests.ErrorValidationTest" name="productErrorValidation" time="0.0">
    <ignored/>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- ErrorValidation Test -->
